name: Grid.ai Training workflow
on: [push]
jobs:
  Train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: bash train.sh
      - run: echo " test"
