name: Grid.ai Training workflow
on: [push]
jobs:
  Train-on-Grird.ai:
    runs-on: ubuntu-latest
    steps:
      - run: pip install -r requirements.txt
      - run: echo "test "
      - run: echo " test"
      - name: Check out repository code
        uses: actions/checkout@v2